[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "fibtable"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

# --8<-- [start:dependencies]
[dependencies]
python = ">=3.14.6,<3.15"
rich = ">=15.0.0,<16"
rust = ">=1.96.0,<1.97"            # we now need a Rust toolchain inside the environment
# --8<-- [end:dependencies]

# --8<-- [start:tasks]
[tasks]
build-cli = "cargo build --release --manifest-path fib/Cargo.toml"
start = { cmd = "python fibtable.py", depends-on = ["build-cli"] }
# --8<-- [end:tasks]
